from app.models import db, Message

seeded_messages = [
    Message(subject_line='Lorem ipsum', content='Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', project_id=1, creator_id=1),
    Message(subject_line='Phasellus interdum egestas venenatis.', content='Maecenas blandit malesuada ultrices. Aenean quam ex, placerat at ultricies ut, sagittis vel velit. Maecenas luctus augue suscipit iaculis tincidunt. Aliquam finibus porttitor augue, scelerisque sodales quam dignissim sit amet. Sed sollicitudin, turpis ut lacinia facilisis, arcu diam interdum augue, et ultrices lacus ligula quis lectus. Pellentesque vel metus a nisi euismod dignissim. Praesent sollicitudin dolor in sem condimentum, nec commodo augue pellentesque. Nam vitae quam eget tortor porttitor accumsan. Duis ornare augue in urna ullamcorper, eu ultrices justo tempus. Nullam quam tellus, posuere at tellus eu, semper porta odio. Vestibulum justo elit, eleifend at tortor non, consectetur posuere sapien. Nam eu dapibus purus. Vestibulum non rhoncus urna.', project_id=1, creator_id=2),
    Message(subject_line='Nam nec enim', content='Nam nec enim quis neque tempor scelerisque a sit amet leo. Fusce pharetra maximus ante quis volutpat. Quisque varius euismod turpis. Nullam eleifend lacus vel erat congue, at ullamcorper sem suscipit. Nam mollis ipsum pellentesque, dictum ipsum quis, ornare mi. Maecenas elementum auctor nibh, non porttitor urna sollicitudin nec. Vestibulum quis tellus eget libero tempor suscipit. Fusce purus erat, luctus vestibulum nisl eu, scelerisque facilisis ipsum. Vivamus porttitor leo et risus bibendum eleifend. Duis sed lectus cursus, placerat nisi et, tincidunt turpis. Sed vitae tortor sed lacus viverra efficitur non vitae urna.', project_id=1, creator_id=4),
    Message(subject_line='Lacinia lectus', content='Integer efficitur lacinia lectus, a imperdiet orci. Maecenas cursus nisl augue. Aliquam erat volutpat. Etiam facilisis lacus vel sollicitudin facilisis. Ut accumsan ex ullamcorper, lacinia nisi eget, eleifend risus. Aenean egestas ornare sagittis. Sed quis ligula ut dui tincidunt egestas ut ut purus. In hac habitasse platea dictumst. Sed porta tortor eu justo efficitur commodo at eu enim. Aenean dolor eros, accumsan at leo a, tincidunt bibendum risus.', project_id=1, creator_id=2),
    Message(subject_line='Sed Tellus', content='Sed arcu tellus, lobortis ut convallis in, ultrices non massa. Aenean sodales ligula et tellus maximus pellentesque. Morbi quam erat, consectetur ac sagittis vitae, interdum at ligula. Nullam sit amet tellus sagittis, fringilla mi et, mollis lacus. Curabitur vel sapien eu lacus sollicitudin dignissim quis nec quam. Integer bibendum rutrum condimentum. Aliquam auctor et magna id dapibus. In tempus sodales ultrices.', project_id=1, creator_id=7),
    
    Message(subject_line='Integer Varius', content='Integer varius efficitur lorem, ut condimentum mi elementum efficitur. Suspendisse gravida leo eu pulvinar tempus. In imperdiet dapibus sapien mollis dapibus. Proin tincidunt dui elit, sit amet scelerisque metus convallis ut. Nullam elit nulla, finibus a euismod id, fermentum eget sem. Mauris tristique a urna quis sodales. Praesent et dolor ut magna suscipit hendrerit. Vestibulum semper consequat tempor. Vivamus ut dapibus turpis. Duis ac augue pharetra, bibendum lacus sed, laoreet mauris. Phasellus elementum dui id eros fringilla, vulputate porta massa consectetur.', project_id=2, creator_id=8),
    Message(subject_line='Vestibulum', content='Vestibulum quis justo at odio luctus bibendum eu quis elit. Praesent non aliquet justo, ac tincidunt augue. Nulla consectetur porta velit vitae pretium. Mauris feugiat lorem tellus, quis semper ipsum consequat et. Nunc aliquet, diam ac bibendum finibus, est ligula porttitor felis, nec egestas ante lectus at diam. Aliquam in purus ut arcu placerat volutpat. Ut eleifend odio eget tellus ullamcorper, a molestie quam pellentesque. Proin in mauris velit. Donec et gravida erat. Phasellus lobortis porta aliquet. Morbi sit amet urna ante. Proin urna metus, tempor eget diam a, cursus vestibulum ex. Morbi eu augue tincidunt, maximus massa nec, feugiat erat. Aenean scelerisque, est vel convallis viverra, orci dolor tempus ipsum, vel vulputate enim elit quis tellus. Interdum et malesuada fames ac ante ipsum primis in faucibus. Quisque pretium lectus sed justo consequat, in elementum purus egestas.', project_id=2, creator_id=3),
    Message(subject_line='Donec', content='Donec malesuada justo sit amet lectus convallis, id pretium arcu bibendum. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Maecenas aliquam tellus diam, in ultricies metus volutpat eu. Morbi eu purus in tellus iaculis lobortis sed at libero. Sed vel nisi ante. Donec ut tincidunt tellus. Curabitur id neque molestie, tempus nisi vitae, fringilla magna. Curabitur ullamcorper sed neque et dignissim. Morbi tempor tortor blandit iaculis posuere. Ut quis tempor velit, rutrum condimentum tellus. Cras est leo, vulputate eu tristique molestie, rutrum ut dui.', project_id=2, creator_id=6),
    Message(subject_line='Maecenas blandit', content='Maecenas blandit malesuada ultrices. Aenean quam ex, placerat at ultricies ut, sagittis vel velit. Maecenas luctus augue suscipit iaculis tincidunt. Aliquam finibus porttitor augue, scelerisque sodales quam dignissim sit amet. Sed sollicitudin, turpis ut lacinia facilisis, arcu diam interdum augue, et ultrices lacus ligula quis lectus. Pellentesque vel metus a nisi euismod dignissim. Praesent sollicitudin dolor in sem condimentum, nec commodo augue pellentesque. Nam vitae quam eget tortor porttitor accumsan. Duis ornare augue in urna ullamcorper, eu ultrices justo tempus. Nullam quam tellus, posuere at tellus eu, semper porta odio. Vestibulum justo elit, eleifend at tortor non, consectetur posuere sapien. Nam eu dapibus purus. Vestibulum non rhoncus urna.', project_id=2, creator_id=8),

  # Message(subject_line='', content='', project_id=, creator_id=),
]


def seed_messages():
  db.session.add_all(seeded_messages)
  db.session.commit()


def undo_messages():
  db.session.execute('TRUNCATE messages RESTART IDENTITY CASCADE;')
  db.session.commit()
