"""create_users_table

Revision ID: ffdc0a98111c
Revises: 
Create Date: 2021-01-18 15:06:02.230689

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ffdc0a98111c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    # Users
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String, nullable=False),
    sa.Column('last_name', sa.String, nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('job_title', sa.String(length=50), nullable=False),
    sa.Column('icon_url', sa.Text(), nullable=True),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )

    # Projects
    op.create_table('projects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text()),
    sa.Column('creator_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.ForeignKeyConstraint(['creator_id'], ['users.id'])
    )

    # Lists 
    op.create_table('lists',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text()),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('creator_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id']),
    sa.ForeignKeyConstraint(['creator_id'], ['users.id'])
    )

    # Todos
    op.create_table('todos', 
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task', sa.String, nullable=False),
    sa.Column('list_id', sa.Integer, nullable=False),
    sa.Column('creator_id', sa.Integer, nullable=False),
    sa.Column('completed', sa.Boolean, nullable=False, default=False),
    sa.Column('due', sa.DateTime, nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.ForeignKeyConstraint(['list_id'], ['lists.id']),
    sa.ForeignKeyConstraint(['creator_id'], ['users.id'])
    )

    # Messages
    op.create_table('messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subject_line', sa.String(length=50), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('creator_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id']),
    sa.ForeignKeyConstraint(['creator_id'], ['users.id']),
    )

    # Comments
    op.create_table('comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('message_id', sa.Integer(), nullable=False),
    sa.Column('creator_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id']),
    sa.ForeignKeyConstraint(['creator_id'], ['users.id']),
    )

    # Users_Todos
    op.create_table('users_todos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('todo_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id']),
    sa.ForeignKeyConstraint(['todo_id'], ['todos.id'])
    )

    #  Users_Projects
    op.create_table('users_projects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id']),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'])
    )

    # ### end Alembic commands ###qqqqqqqqq

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users_projects')
    op.drop_table('users_todos')
    op.drop_table('todos')
    op.drop_table('lists')
    op.drop_table('comments')
    op.drop_table('messages')
    op.drop_table('projects')
    op.drop_table('users')
    # ### end Alembic commands ###
